/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testingsqlconnection.view;

import com.mycompany.testingsqlconnection.Conexion;
import com.mycompany.testingsqlconnection.controller.IEmployeController;
import com.mycompany.testingsqlconnection.controller.impl.EmployeControllerImpl;
import com.mycompany.testingsqlconnection.model.Employed;

import java.sql.ResultSet;
import java.sql.SQLException;

import static com.mycompany.testingsqlconnection.utils.GenderEnumParsing.parseGender;

/**
 *
 * @author alexi
 */
public class PanelDeControl extends javax.swing.JFrame {

    IEmployeController employeController;

    /**
     * Creates new form PanelDeControl
     */
    public PanelDeControl() {
        initComponents();
        employeController = new EmployeControllerImpl();
        SEARCHBUTTON.setLabel("Search");
        SAVEBUTTON.setLabel("Guardar");
        DELETEBUTTON.setLabel("Delete");
        UPDATEBUTTON.setLabel("Actualizar");
        CLEARBUTTON.setLabel("Limpiar");
        GENERO.addItem("MALE");
        GENERO.addItem("FEMALE");
        GENERO.addItem("OTHER");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CLEARBUTTON1 = new javax.swing.JButton();
        button4 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        KEY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DOMICILIO = new javax.swing.JTextField();
        FECHA = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JTextField();
        NOMBRE = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        SEARCHBUTTON = new java.awt.Button();
        DELETEBUTTON = new java.awt.Button();
        UPDATEBUTTON = new java.awt.Button();
        CLEARBUTTON = new java.awt.Button();
        SAVEBUTTON = new java.awt.Button();
        GENERO = new java.awt.Choice();

        CLEARBUTTON1.setText("LIMPIAR");

        button4.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CLAVE:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("FECHA NACIMIENTO:");

        jLabel4.setText("TELEFONO:");

        jLabel5.setText("DOMICILIO:");

        jLabel6.setText("EMAIL:");

        jLabel7.setText("GENERO:");

        TELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELEFONOActionPerformed(evt);
            }
        });

        SEARCHBUTTON.setLabel("button1");
        SEARCHBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHBUTTONActionPerformed(evt);
            }
        });

        DELETEBUTTON.setLabel("button1");
        DELETEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEBUTTONActionPerformed(evt);
            }
        });

        UPDATEBUTTON.setLabel("button1");
        UPDATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEBUTTONActionPerformed(evt);
            }
        });

        CLEARBUTTON.setLabel("button1");
        CLEARBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARBUTTONActionPerformed(evt);
            }
        });

        SAVEBUTTON.setLabel("button1");
        SAVEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(FECHA, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(TELEFONO, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(DOMICILIO, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(KEY)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(GENERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(SAVEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(DELETEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UPDATEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLEARBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(SEARCHBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(KEY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SEARCHBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DOMICILIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UPDATEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLEARBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVEBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SEARCHBUTTONActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            Employed employed = employeController.searchEmployed(Long.parseLong(KEY.getText()));NOMBRE.setText(employed.getName());
            DOMICILIO.setText(employed.getAddress());
            TELEFONO.setText(employed.getPhoneNumber());
            FECHA.setText(employed.getBirthDate());
            EMAIL.setText(employed.getEmail());
            GENERO.select(employed.getGender().toString());
        }
        catch(SQLException e){
            e.printStackTrace();
        }

    }

    private void UPDATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEBUTTONActionPerformed

        Employed employed = Employed.builder()
                .name(NOMBRE.getText())
                .address(DOMICILIO.getText())
                .phoneNumber(TELEFONO.getText())
                .birthDate(FECHA.getText())
                .email(EMAIL.getText())
                .gender(parseGender(GENERO.getSelectedItem()))
                .build();

        try {
            Boolean wasUpdated = employeController.updateEmployed(employed, Long.parseLong(KEY.getText()));
            if (!wasUpdated) {
                clearFields();
            } else {
                System.out.println("Empleado no actualizado");
            }
        }
        catch(SQLException e) {
            e.printStackTrace();
        }
    }

    private void SAVEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {
        Employed employed = Employed.builder()
                .name(NOMBRE.getText())
                .address(DOMICILIO.getText())
                .phoneNumber(TELEFONO.getText())
                .birthDate(FECHA.getText())
                .email(EMAIL.getText())
                .gender(parseGender(GENERO.getSelectedItem()))
                .build();


        try {
            Boolean response = employeController.saveEmployed(employed);
            if (!response) {
                clearFields();
            } else {
                System.out.println("Empleado no guardado");
            }
            clearFields();
        }
        catch(SQLException e) {
            e.printStackTrace();
        }
    }

    private void TELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TELEFONOActionPerformed

    private void CLEARBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARBUTTONActionPerformed
        clearFields();
       ;
    }//GEN-LAST:event_CLEARBUTTONActionPerformed

    private void DELETEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEBUTTONActionPerformed
        try {
            Boolean resultSet = employeController.deleteEmployed(Long.parseLong(KEY.getText()));
            if (!resultSet) {
                clearFields();

            } else {

            }
        }
        catch(SQLException e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        KEY.setText("");
        NOMBRE.setText("");
        DOMICILIO.setText("");
        TELEFONO.setText("");
        FECHA.setText("");
        EMAIL.setText("");
        GENERO.select("MALE");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button CLEARBUTTON;
    private javax.swing.JButton CLEARBUTTON1;
    private java.awt.Button DELETEBUTTON;
    private javax.swing.JTextField DOMICILIO;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField FECHA;
    private java.awt.Choice GENERO;
    private javax.swing.JTextField KEY;
    private javax.swing.JTextField NOMBRE;
    private java.awt.Button SAVEBUTTON;
    private java.awt.Button SEARCHBUTTON;
    private javax.swing.JTextField TELEFONO;
    private java.awt.Button UPDATEBUTTON;
    private java.awt.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;

    // End of variables declaration//GEN-END:variables
}
